name: Windows build

on:
  push:
    tags: [ 'v*' ]   # push tag v1.0.0 sẽ kích hoạt luôn
  workflow_dispatch:

permissions:
  contents: write   # cần để tạo GitHub Release

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller==6.16.0

      - name: Stamp version into env & file
        shell: pwsh
        run: |
          $ver = "${{ github.ref_name }}"
          if ($env:GITHUB_REF_TYPE -eq "tag") { $ver = $ver.TrimStart('v') } else { $ver = "0.0.0-dev" }
          "PAPERFORGE_VERSION=$ver"        | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "PAPERFORGE_REPO=minhquach8/paperforge" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          # Tạo file JSON để nhúng vào app
          @"
          { "version": "$ver" }
          "@ | Set-Content shared\paperforge_build.json -Encoding utf8

      - name: Verify build stamp file exists
        shell: pwsh
        run: |
          if (-not (Test-Path shared\paperforge_build.json)) {
            Write-Host "Expected file not found: shared\paperforge_build.json"
            Get-ChildItem -Recurse shared | ForEach-Object { $_.FullName }
            throw "paperforge_build.json missing"
          }

      # (TÙY CHỌN) In version từ shared/version.py nếu bạn có file này
      - name: Read app version
        id: ver
        run: |
          try {
            $v = python -c "from shared.version import APP_VERSION; print(APP_VERSION)"
          } catch {
            $v = "0.0.0-dev"
          }
          echo "version=$v" >> $env:GITHUB_OUTPUT

      - name: Build Student (PyInstaller)
        run: pyinstaller -y packaging\win_student.spec

      - name: Build Supervisor (PyInstaller)
        run: pyinstaller -y packaging\win_supervisor.spec

      - name: Show dist tree (debug)
        run: |
          Write-Host "== dist =="
          Get-ChildItem -Recurse -Force dist | ForEach-Object { $_.FullName }

      # Đóng gói ZIP, KHÔNG phụ thuộc tên thư mục cố định
      - name: Zip portable bundles
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null

          $superDir = Get-ChildItem -Path dist -Directory | Where-Object { $_.Name -match 'Supervisor' } | Select-Object -First 1
          if (-not $superDir) { throw "Không tìm thấy thư mục Supervisor trong dist." }
          $superZip = "dist\Paperforge-Supervisor-Portable-win64.zip"
          if (Test-Path $superZip) { Remove-Item $superZip -Force }
          Compress-Archive -Path "$($superDir.FullName)\*" -DestinationPath $superZip -Force

          $studDir = Get-ChildItem -Path dist -Directory | Where-Object { $_.Name -match 'Student' } | Select-Object -First 1
          if (-not $studDir) { throw "Không tìm thấy thư mục Student trong dist." }
          $studZip = "dist\Paperforge-Student-Portable-win64.zip"
          if (Test-Path $studZip) { Remove-Item $studZip -Force }
          Compress-Archive -Path "$($studDir.FullName)\*" -DestinationPath $studZip -Force

          Write-Host "Zipped:"
          Get-Item dist\*.zip | ForEach-Object { $_.FullName }

      - name: Upload portable artifacts
        uses: actions/upload-artifact@v4
        with:
          name: paperforge-portable-${{ steps.ver.outputs.version }}
          path: |
            dist/Paperforge-Supervisor-Portable-win64.zip
            dist/Paperforge-Student-Portable-win64.zip
          if-no-files-found: error

      # Chỉ tạo Release khi workflow chạy do push tag (refs/tags/*)
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}   # v1.0.0
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/Paperforge-Supervisor-Portable-win64.zip
            dist/Paperforge-Student-Portable-win64.zip
