name: Windows build

on:
  workflow_dispatch:    # allow manual "Run workflow"
  push:
    tags: ["v*"]        # auto build when pushing tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    env:
      TECTONIC_VER: "0.15.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6

      - name: Prepare vendor Tectonic (download on CI)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path vendor\tectonic\windows-x86_64 | Out-Null
          $url = "https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic%40${env:TECTONIC_VER}/tectonic-${env:TECTONIC_VER}-x86_64-pc-windows-msvc.zip"
          Write-Host "Downloading $url"
          Invoke-WebRequest -Uri $url -OutFile tectonic.zip
          Expand-Archive tectonic.zip -DestinationPath vendor\tectonic\windows-x86_64 -Force
          $folder = Get-ChildItem vendor\tectonic\windows-x86_64 | Where-Object { $_.PSIsContainer -and $_.Name -like "tectonic-*" } | Select-Object -First 1
          if (-not $folder) { throw "Tectonic folder not found after extraction." }
          Copy-Item "$($folder.FullName)\tectonic.exe" vendor\tectonic\windows-x86_64\tectonic.exe -Force
          Remove-Item tectonic.zip

      - name: Build Student (PyInstaller)
        run: pyinstaller packaging\win_student.spec

      - name: Build Supervisor (PyInstaller)
        run: pyinstaller packaging\win_supervisor.spec

      - name: Upload portable artefacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable
          path: |
            dist/Paperforge Student/**
            dist/Paperforge Supervisor/**

      # Optional: create .exe installers with Inno Setup
      - name: Install Inno Setup
        run: choco install innosetup -y
      - name: Build Student Installer
        run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" packaging\student.iss'
      - name: Build Supervisor Installer
        run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" packaging\supervisor.iss'

      - name: Upload installers
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-installers
          path: |
            dist/Paperforge-Student-Setup.exe
            dist/Paperforge-Supervisor-Setup.exe
